name: Generate Commit History Excel Report

on:
  workflow_dispatch:  # Manual trigger

jobs:
  generate-commit-excel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openpyxl

      - name: Extract commit history and write to Excel
        run: |
          mkdir output
          git log --pretty=format:"%h|%an|%ad|%s" --date=short > commits.txt
          
          python <<EOF
          import openpyxl

          wb = openpyxl.Workbook()
          ws = wb.active
          ws.title = "Commits"
          ws.append(["SHA", "Author", "Date", "Message"])

          with open("commits.txt") as f:
              for line in f:
                  parts = line.strip().split("|", 3)
                  if len(parts) == 4:
                      ws.append(parts)

          wb.save("output/commit_history.xlsx")
          EOF

      - name: Upload Excel as artifact
        uses: actions/upload-artifact@v4
        with:
          name: commit-history-excel
          path: output/commit_history.xlsx
